In [ ]:
import numpy as np
import pandas as pd
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

# Load dataset
df = pd.read_csv("../data/Groceries_dataset.csv")

# Check dataset
print(df.isnull().sum())

# Convert Date column to datetime
df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)

# Extract features from Date
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day
df["DayOfWeek"] = df["Date"].dt.dayofweek

# Features and target
X = df[
    [
        "Member_number",
        "Year",
        "Month",
        "Day",
        "DayOfWeek"
    ]
]

y = df["itemDescription"]

# Split data into training and testing
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42
)

# Standardization
sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Check whether StandardScaler worked
print("Mean:", X_train.mean(axis=0))
print("Std:", X_train.std(axis=0))

# Create Decision Tree classifier
classifier = DecisionTreeClassifier(
    criterion="entropy",
    random_state=0
)

# Train the model
classifier.fit(X_train, y_train)

# Predict test data
y_pred = classifier.predict(X_test)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy * 100, "%")

# Classification Report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Predict an example transaction
new_transaction = np.array([[
    1808,       # Member_number
    2015,       # Year
    7,          # Month
    21,         # Day
    1           # DayOfWeek
]])

# Scale using the existing scaler
new_transaction_scaled = sc.transform(new_transaction)

# Predict
prediction = classifier.predict(new_transaction_scaled)

print("Predicted Item:", prediction[0])

# Plot Decision Tree
tree.plot_tree(classifier)

Member_number      0
Date               0
itemDescription    0
dtype: int64
Mean: [ 1.09979786e-17  2.65153931e-14 -1.95519619e-17  6.84318667e-17
 -9.28718191e-18]
Std: [1. 1. 1. 1. 1.]
Confusion Matrix:
[[ 0  0  0 ...  0  0  0]
 [ 0  1  0 ...  3  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 3  6  0 ... 22 10  0]
 [ 0  5  0 ... 16  4  0]
 [ 0  1  0 ...  0  2  0]]
Accuracy: 1.6611638464713165 %
Classification Report:
                           precision    recall  f1-score   support

    Instant food products       0.00      0.00      0.00        15
                 UHT-milk       0.01      0.01      0.01        87
         abrasive cleaner       0.00      0.00      0.00         8
         artif. sweetener       0.00      0.00      0.00         7
                     bags       0.00      0.00      0.00         1
            baking powder       0.02      0.04      0.02        28
         bathroom cleaner       0.00      0.00      0.00         3
                     beef       0.02      0.04  

c:\Users\bda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\bda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\bda\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier

KeyboardInterrupt: 