In [1]:
import numpy as np

a = np.full((2, 2), 7)

print(a)

[[7 7]
 [7 7]]


In [2]:
a = np.random.random((2, 2))

print(a)

[[0.02215067 0.93518141]
 [0.32313189 0.27772548]]


In [3]:
a = np.arange(10, 51)

print("Array:", a)
print("Number of elements:", a.size)
print("Shape:", a.shape)
print("Dimension:", a.ndim)
print("Data type:", a.dtype)

Array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
Number of elements: 41
Shape: (41,)
Dimension: 1
Data type: int64


In [4]:
# 10 zeros
a = np.zeros(10)
print("Zeros:", a)

# 3 x 3 ones
b = np.ones((3, 3))
print("Ones:\n", b)

# 4 x 4 identity matrix
c = np.eye(4)
print("Identity matrix:\n", c)

# Numbers from 5 to 50 with step 5
d = np.arange(5, 51, 5)
print("Numbers:", d)

Zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Numbers: [ 5 10 15 20 25 30 35 40 45 50]


In [5]:
a = np.arange(1, 25)

a1 = a.reshape(4, 6)
a2 = a.reshape(6, 4)
a3 = a.reshape(2, 3, 4)

print("4 x 6:")
print(a1)
print("Shape:", a1.shape)
print("Dimension:", a1.ndim)

print("\n6 x 4:")
print(a2)
print("Shape:", a2.shape)
print("Dimension:", a2.ndim)

print("\n2 x 3 x 4:")
print(a3)
print("Shape:", a3.shape)
print("Dimension:", a3.ndim)

4 x 6:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)
Dimension: 2

6 x 4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Shape: (6, 4)
Dimension: 2

2 x 3 x 4:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)
Dimension: 3


In [6]:
marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])

print("First element:", marks[0])
print("Last element:", marks[-1])
print("Third element:", marks[2])
print("First four elements:", marks[:4])
print("Last three elements:", marks[-3:])

First element: 78
Last element: 81
Third element: 92
First four elements: [78 85 92 67]
Last three elements: [73 95 81]


In [7]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Square of a:", a ** 2)

Addition: [15 30 45 60 75]
Subtraction: [ 5 10 15 20 25]
Multiplication: [  50  200  450  800 1250]
Division: [2. 2. 2. 2. 2.]
Square of a: [ 100  400  900 1600 2500]


In [8]:
salary = np.array([25000, 32000, 28000, 45000,
                   50000, 38000, 42000, 30000])

print("Total:", np.sum(salary))
print("Average:", np.mean(salary))
print("Highest:", np.max(salary))
print("Lowest:", np.min(salary))
print("Median:", np.median(salary))
print("Standard deviation:", np.std(salary))

Total: 290000
Average: 36250.0
Highest: 50000
Lowest: 25000
Median: 35000.0
Standard deviation: 8317.902379807063


In [9]:
marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])

print("Marks greater than 75:", marks[marks > 75])

print("Marks between 50 and 80:",
      marks[(marks >= 50) & (marks <= 80)])

below_50 = np.sum(marks < 50)
print("Students below 50:", below_50)

above_60 = np.sum(marks >= 60)
percentage = (above_60 / len(marks)) * 100

print("Percentage scoring 60 or above:", percentage, "%")

Marks greater than 75: [78 89 90 76 84]
Marks between 50 and 80: [78 67 55 76]
Students below 50: 3
Percentage scoring 60 or above: 60.0 %


In [10]:
marks = np.array([
    [80, 75, 90],
    [65, 70, 72],
    [88, 92, 85],
    [55, 60, 58]
])

total = np.sum(marks, axis=1)
average = np.mean(marks, axis=1)
subject_average = np.mean(marks, axis=0)
highest_student = np.argmax(total)
highest_subject = np.max(marks, axis=0)

print("Total marks:", total)
print("Average marks:", average)
print("Average in each subject:", subject_average)
print("Student with highest total:", highest_student + 1)
print("Highest mark in each subject:", highest_subject)

Total marks: [245 207 265 173]
Average marks: [81.66666667 69.         88.33333333 57.66666667]
Average in each subject: [72.   74.25 76.25]
Student with highest total: 3
Highest mark in each subject: [88 92 90]


In [11]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("Matrix addition:")
print(A + B)

print("\nElement-wise multiplication:")
print(A * B)

print("\nMatrix multiplication:")
print(A @ B)

print("\nTranspose of A:")
print(A.T)

Matrix addition:
[[ 6  8]
 [10 12]]

Element-wise multiplication:
[[ 5 12]
 [21 32]]

Matrix multiplication:
[[19 22]
 [43 50]]

Transpose of A:
[[1 3]
 [2 4]]


A * B  → element-by-element multiplication

A @ B  → matrix multiplication

In [12]:
temperature = np.array([
    31, 32, 33, 35, 36, 34, 32,
    30, 29, 31, 33, 35, 37, 36
])

average = np.mean(temperature)

print("Mean:", average)
print("Maximum:", np.max(temperature))
print("Minimum:", np.min(temperature))

print("Days above average:",
      np.sum(temperature > average))

print("Temperatures greater than 34:",
      temperature[temperature > 34])

print("Difference:",
      np.max(temperature) - np.min(temperature))

print("Standard deviation:",
      np.std(temperature))

Mean: 33.142857142857146
Maximum: 37
Minimum: 29
Days above average: 6
Temperatures greater than 34: [35 36 35 37 36]
Difference: 8
Standard deviation: 2.356060357495806


In [13]:
sales = np.array([
    12000, 15000, 17000, 14000,
    18000, 21000, 19000, 22000,
    25000, 23000, 26000, 28000
])

print("Total annual sales:", np.sum(sales))
print("Average monthly sales:", np.mean(sales))

highest_month = np.argmax(sales) + 1
lowest_month = np.argmin(sales) + 1

print("Month with highest sales:", highest_month)
print("Month with lowest sales:", lowest_month)

print("Months above 20,000:",
      np.sum(sales > 20000))

percentage_increase = ((sales[-1] - sales[0]) / sales[0]) * 100

print("Percentage increase:", percentage_increase, "%")

Total annual sales: 240000
Average monthly sales: 20000.0
Month with highest sales: 12
Month with lowest sales: 1
Months above 20,000: 6
Percentage increase: 133.33333333333331 %


In [14]:
marks = np.array([
    [78, 85, 90, 88],
    [65, 70, 72, 68],
    [92, 88, 95, 91],
    [55, 60, 58, 62],
    [80, 75, 82, 79]
])

total = np.sum(marks, axis=1)
average = np.mean(marks, axis=1)
subject_average = np.mean(marks, axis=0)

print("Total marks:", total)
print("Average of every student:", average)
print("Average of every subject:", subject_average)

highest_student = np.argmax(average) + 1
lowest_student = np.argmin(average) + 1

print("Highest-scoring student:", highest_student)
print("Lowest-scoring student:", lowest_student)

print("Students with average greater than 80:",
      np.where(average > 80)[0] + 1)

print("Overall class average:", np.mean(marks))

# Performance categories
category = np.select(
    [
        average >= 85,
        average >= 70,
        average >= 50
    ],
    [
        "Excellent",
        "Good",
        "Average"
    ],
    default="Needs Improvement"
)

print("Performance categories:", category)

Total marks: [341 275 366 235 316]
Average of every student: [85.25 68.75 91.5  58.75 79.  ]
Average of every subject: [74.  75.6 79.4 77.6]
Highest-scoring student: 3
Lowest-scoring student: 4
Students with average greater than 80: [1 3]
Overall class average: 76.65
Performance categories: ['Excellent' 'Average' 'Excellent' 'Average' 'Good']


In [15]:
a = np.random.randint(1, 101, 20)

print(a)

[ 66  75   5  65  89  30  27  63  12  56  46   6  87 100   6  37  52  38
  63  13]


In [16]:
print(a[a % 2 == 0])

[ 66  30  12  56  46   6 100   6  52  38]


In [17]:
a[a < 50] = 0

print(a)

[ 66  75   0  65  89   0   0  63   0  56   0   0  87 100   0   0  52   0
  63   0]


In [18]:
print("Ascending:", np.sort(a))

print("Descending:", np.sort(a)[::-1])

Ascending: [  0   0   0   0   0   0   0   0   0   0  52  56  63  63  65  66  75  87
  89 100]
Descending: [100  89  87  75  66  65  63  63  56  52   0   0   0   0   0   0   0   0
   0   0]


In [19]:
values, counts = np.unique(a, return_counts=True)

print("Unique values:", values)
print("Frequencies:", counts)

Unique values: [  0  52  56  63  65  66  75  87  89 100]
Frequencies: [10  1  1  2  1  1  1  1  1  1]


In [20]:
matrix = np.random.randint(1, 101, (5, 5))

print("Matrix:")
print(matrix)

print("Row-wise means:")
print(np.mean(matrix, axis=1))

print("Column-wise means:")
print(np.mean(matrix, axis=0))

Matrix:
[[46 30 49 35 10]
 [92 44 90 25 58]
 [39 67 87 81 39]
 [65 12 45 16 69]
 [22 12 12 92 51]]
Row-wise means:
[34.  61.8 62.6 41.4 37.8]
Column-wise means:
[52.8 33.  56.6 49.8 45.4]


In [21]:
a = np.array([10, 20, 30, 40, 50])

normalized = (a - np.min(a)) / (np.max(a) - np.min(a))

print("Original:", a)
print("Normalized:", normalized)

Original: [10 20 30 40 50]
Normalized: [0.   0.25 0.5  0.75 1.  ]


In [22]:
a = np.array([10, 20, 30, 40, 50])

standardized = (a - np.mean(a)) / np.std(a)

print("Original:", a)
print("Standardized:", standardized)

Original: [10 20 30 40 50]
Standardized: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [23]:
marks = np.random.randint(0, 101, 100)

print("Marks:")
print(marks)

print("0-39:", np.sum((marks >= 0) & (marks <= 39)))
print("40-59:", np.sum((marks >= 40) & (marks <= 59)))
print("60-79:", np.sum((marks >= 60) & (marks <= 79)))
print("80-100:", np.sum((marks >= 80) & (marks <= 100)))

Marks:
[40 67 40  6 18 47  7 70 30 25 62 94 26 92 69 32 87 15 61 48 67 82 63 23
  0 27 40 75 31 56 44  5 78 30 10 75  7 46  1 74 41  8 65 36 29  0 27 26
 60 39 83 15 76 21 53 69 17 54 95 63 85 42 97 40 30  2 93 11 44 77  6 12
 25 42  1 42 31 89 73 43 77  2 18 28 51  1 45 60  2 48 71 96 26 48  0 52
 29  7 65 30]
0-39: 45
40-59: 22
60-79: 22
80-100: 11


In [24]:
import time
import numpy as np

# Python list
list1 = list(range(1000000))
list2 = list(range(1000000))

start = time.time()

result = [a * b for a, b in zip(list1, list2)]

list_time = time.time() - start


# NumPy array
array1 = np.arange(1000000)
array2 = np.arange(1000000)

start = time.time()

result = array1 * array2

numpy_time = time.time() - start


print("Python list time:", list_time)
print("NumPy array time:", numpy_time)

Python list time: 0.027033567428588867
NumPy array time: 0.0
